services:
  - type: web
    name: verifast-newsbot
    env: node
    buildCommand: ./render-build.sh
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 3001
      - key: REDIS_URL
        fromService:
          type: redis
          name: newsbot-redis
          property: connectionString
      - key: QDRANT_HOST
        value: http://localhost:6333
      - key: GEMINI_API_KEY
        sync: false
      - key: JINA_API_KEY
        sync: false

  - type: redis
    name: newsbot-redis
    ipAllowList: []
    plan: free
